### ISSUE TITLE
Rangee is not a constructor

### ISSUE THREAD

**Issue by minkuan** [LukasRada/rangee#15]
used in ts, like this:

`
import Rangee from 'rangee'

const rangee = new Rangee.Rangee({ document })`

chrome complains: Uncaught TypeError: r(...).Rangee is not a constructor

**Comment by LukasRada** [comment]
Have you tried it like this in example? https://github.com/LukasRada/rangee/blob/master/examples/nextjs/src/app/page.tsx#L12
But otherwise I will try to reproduce it in the next.js example

**Comment by LukasRada** [comment]
Oh I see now. The Rangee is named export and not default export.
Please fix your code so the import is like named import and not default:
```
import { Rangee } from 'rangee'
```
And used like this:
```
const rangee = new Rangee({ document })
```

**Comment by LukasRada** [comment]
The README.md was incorrect in basic example seciont. Now it is fixed. Thanks for the report.
