### ISSUE TITLE
Fails when Range starts at top of the HTML body

### ISSUE THREAD

**Issue by danielktaylor** [LukasRada/rangee#7]
Fails when range.commonAncestorContainer == range.startContainer in index.ts. startFound is always False.

An example of when this happens is selecting the range at the top of this page to the end.

```
<html>
   <head>
      <meta content="text/html; charset=UTF-8" http-equiv="content-type">
      <script src="script.js" type="module"></script>
   </head>
   <body class="whatever">
      <br/>
      <br/>
      start
      <span>end</span>
   </body>
</html>
```

Naive fix: (not sure if there are side effects, still testing)

Change: 

```
let node: Node | null;
while (node = treeWalker.nextNode()) {
...
}
```

To:

```
let node = treeWalker.root;
do {
...
} while (node = treeWalker.nextNode());
```

**Comment by LukasRada** [comment]
Fixed.
Unit test with the provided HTML here: https://github.com/LukasRada/rangee/blob/master/tests/Rangee.test.ts#L88
(By the way I am refactoring the whole solution, I got 100% unit test coverage but will add also e2e test)
